version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    restart: always
#    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  zipkin:
    image: openzipkin/zipkin
    restart: always
#    container_name: zipkin
    ports:
      - "9411:9411"

  eureka-server:
    build:
      context: ./EurekaServerConfiguration
      dockerfile: Dockerfile
#    container_name: eureka-server
    ports:
      - "8085:8085"
    environment:
      - EUREKA_SERVER_PORT=8085

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
#    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/userData
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8085/eureka
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
    depends_on:
      - eureka-server
      - mongodb

  customer-service:
    build:
      context: ./CustomerService
      dockerfile: Dockerfile
#    container_name: customer-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/customerData
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8085/eureka
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
    depends_on:
      - eureka-server
      - mongodb

  invoice-service:
    build:
      context: ./InvoiceService
      dockerfile: Dockerfile
#    container_name: invoice-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/invoiceData
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8085/eureka
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
    depends_on:
      - eureka-server
      - mongodb

  api-gateway:
    build:
      context: ./APIGateWay
      dockerfile: Dockerfile
#    container_name: api-gateway
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8085/eureka
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
    depends_on:
      - eureka-server
      - user-service
      - customer-service
      - invoice-service

volumes:
  mongo_data:
