
      
      
server:
  port: 8090


spring:
  application:
    name: API-GATEWAY-SERVER
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /users/**, /api/users/**, /
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**,/api/customers/**, /customers/**
        - id: INVOICE-SERVICE
          uri: lb://INVOICE-SERVICE
          predicates:
            - Path=/api/v1/invoices/**,/api/invoices/**, /invoices
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

    
  
        

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8085/eureka








      
      
      